// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"github.com/hailong-bot/go-galaxy/rpc/grpc/zero/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user",
				Handler: userHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.LoginVerification},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/createUser",
					Handler: createUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/userinfo",
					Handler: getUserHandler(serverCtx),
				},
			}...,
		),
	)
}
