// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CreateUserReq struct {
	Name   string `json:"name"`
	Mobile string `json:"mobile"`
}

type CreateUserResp struct {
	Id int64 `json:"id"`
}

type UserReq struct {
	Id string `json:"id"`
}

type UserResp struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone"`
}
